server.port=8080

spring.application.name=banco-austro

datasources.cuenca.url=jdbc:postgresql://localhost:5432/banco_cuenca
datasources.cuenca.username=banco
datasources.cuenca.password=banco123

datasources.quito.url=jdbc:postgresql://localhost:5433/banco_quito
datasources.quito.username=banco
datasources.quito.password=banco123